// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorWithCode is an autogenerated mock type for the ErrorWithCode type
type ErrorWithCode struct {
	mock.Mock
}

type ErrorWithCode_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorWithCode) EXPECT() *ErrorWithCode_Expecter {
	return &ErrorWithCode_Expecter{mock: &_m.Mock}
}

// Code provides a mock function with no fields
func (_m *ErrorWithCode) Code() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ErrorWithCode_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type ErrorWithCode_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *ErrorWithCode_Expecter) Code() *ErrorWithCode_Code_Call {
	return &ErrorWithCode_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *ErrorWithCode_Code_Call) Run(run func()) *ErrorWithCode_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorWithCode_Code_Call) Return(_a0 int) *ErrorWithCode_Code_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorWithCode_Code_Call) RunAndReturn(run func() int) *ErrorWithCode_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with no fields
func (_m *ErrorWithCode) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ErrorWithCode_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ErrorWithCode_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *ErrorWithCode_Expecter) Error() *ErrorWithCode_Error_Call {
	return &ErrorWithCode_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *ErrorWithCode_Error_Call) Run(run func()) *ErrorWithCode_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorWithCode_Error_Call) Return(_a0 string) *ErrorWithCode_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorWithCode_Error_Call) RunAndReturn(run func() string) *ErrorWithCode_Error_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorWithCode creates a new instance of ErrorWithCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorWithCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorWithCode {
	mock := &ErrorWithCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
